### ISSUE TITLE
 Forbidden! When accessing bintray release 

### ISSUE THREAD

**Issue by gauravcanon** [susonthapa/curved-bottom-navigation#17] opened 2021-08-21 05:27 UTC
```
Could not GET 'https://dl.bintray.com/susonthapa/curved-bottom-navigation/np/com/susanthapa/curved_bottom_navigation/latest_version/curved_bottom_navigation-latest_version.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
```

`https://dl.bintray.com/susonthapa/curved-bottom-navigation`

**The above URL is also Forbidden**

After solving above suddenly this appear 

```
Could not GET 'https://dl.bintray.com/susonthapa/curved-bottom-navigation/android/arch/persistence/room/rxjava2/2.3.0-beta03/rxjava2-2.3.0-beta03.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
```

**Comment by susonthapa** [comment] 2021-08-21 10:29
Duplicate of #11

**Closed as completed** 2022-11-21 03:38 UTC
